# Generated by Django 3.2.7 on 2021-09-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline', models.PositiveIntegerField(default=0, verbose_name='Meters in offline')),
                ('online_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.account')),
            ],
            options={
                'verbose_name_plural': 'leaderboard entries',
            },
        ),
    ]
